version: '3.5'

networks: 
    net-backend:
        driver: bridge
        
services:
    
    postgresdb:
        build: 
            dockerfile: ./docker/postgres.dockerfile
            context: .
        image: carlosmedeiroslima/postgresdb
        container_name: postgresdb
        ports:
            - "5432:5432"
        networks:
            - net-backend
        volumes: 
            - ./dados/infra/database:/var/lib/postgresql/data
        restart: always
        environment:
            #- ./development.env
            - POSTGRES_DB=app
            - POSTGRES_USER=dockerapp
            - POSTGRES_PASSWORD=root
