server:
  port: 8086

spring:

  application:
    name: fornecedor

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
