server:
  port: 8086

spring:

  application:
    name: fornecedor

  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka